export const blocosData = [
  {
    id: 1,
    dia: "Sexta",
    data: "06/02",
    nome: "Vai dar tudo certo",
    horario: "19:45",
    local: "Rua da Matriz",
    descricao: "",
  },
  {
    id: 2,
    dia: "Sábado",
    data: "07/02",
    nome: "Acorda Bezerros",
    horario: "23:00",
    local: "Rua 15 de Novembro",
    descricao: "",
  },
  {
    id: 3,
    dia: "Domingo",
    data: "08/02",
    nome: "Papangu és tu?",
    horario: "10:00",
    local: "Rua Vitoriano Pereira de Lima",
    descricao: "",
  },
  {
    id: 4,
    dia: "Domingo",
    data: "08/02",
    nome: "Pior é nada",
    horario: "14:00",
    local: "Rua Espanha",
    descricao: "",
  },
  {
    id: 5,
    dia: "Domingo",
    data: "11/02",
    nome: "Movimento na Folia",
    horario: "16:00",
    local: "São Sebastião",
    descricao: "",
  },
  {
    id: 6,
    dia: "Domingo",
    data: "11/02",
    nome: "Educarnaval",
    horario: "20:30",
    local: "São Sebastião",
    descricao: "",
  },
  {
    id: 7,
    dia: "Quinta",
    data: "12/02",
    nome: "SEMP Folia",
    horario: "09:00",
    local: "São Sebastião",
    descricao: "",
  },
  {
    id: 8,
    dia: "Quinta",
    data: "12/02",
    nome: "Folia da Boa Idade",
    horario: "13:30",
    local: "São Sebastião",
    descricao: "",
  },
  {
    id: 9,
    dia: "Quinta",
    data: "12/02",
    nome: "Corredores Noturnos de Bezerros",
    horario: "19:00",
    local: "São Sebastião",
    descricao: "",
  },
  {
    id: 10,
    dia: "Quinta",
    data: "12/02",
    nome: "Na Batida e No Frevo",
    horario: "20:00",
    local: "São Sebastião",
    descricao: "",
  },
  {
    id: 11,
    dia: "Quinta",
    data: "12/02",
    nome: "Risotril",
    horario: "20:30",
    local: "São Sebastião",
    descricao: "",
  },
  {
    id: 12,
    dia: "Quinta",
    data: "12/02",
    nome: "Óia o Chico",
    horario: "21:30",
    local: "Restaurante Lá em Casa",
    descricao: "",
  },
  {
    id: 13,
    dia: "Sexta",
    data: "13/02",
    nome: "EduPapangu I",
    horario: "08:30",
    local: "São Sebastião",
    descricao: "",
  },
  {
    id: 14,
    dia: "Sexta",
    data: "13/02",
    nome: "Batatão Folia",
    horario: "19:00",
    local: "Rua Henrique Dias",
    descricao: "",
  },
  {
    id: 15,
    dia: "Sexta",
    data: "13/02",
    nome: "Balé da Kika",
    horario: "19:30",
    local: "Av. Professor Amaral",
    descricao: "",
  },
  {
    id: 16,
    dia: "Sexta",
    data: "13/02",
    nome: "EduPapangu II",
    horario: "14:30",
    local: "São Sebastião",
    descricao: "",
  },
  {
    id: 17,
    dia: "Sexta",
    data: "13/02",
    nome: "Bloco To No SUAS",
    horario: "17:00",
    local: "São Sebastião",
    descricao: "",
  },
  {
    id: 18,
    dia: "Sexta",
    data: "13/02",
    nome: "Bloco Cafofo",
    horario: "20:00",
    local: "Av. Presidente Kenedy",
    descricao: "",
  },
  {
    id: 19,
    dia: "Sábado",
    data: "14/02",
    nome: "A Casa Caiu",
    horario: "14:00",
    local: "Sapucarana - Rua principal",
    descricao: "",
  },
  {
    id: 20,
    dia: "Sábado",
    data: "14/02",
    nome: "Catraias do Cruzeiro",
    horario: "15:00",
    local: "Campo do Cruzeiro",
    descricao: "",
  },
  {
    id: 21,
    dia: "Sábado",
    data: "14/02",
    nome: "Bloco do Biu",
    horario: "18:00",
    local: "São Sebastião",
    descricao: "",
  },
  {
    id: 22,
    dia: "Sábado",
    data: "14/02",
    nome: "Libera o Toin",
    horario: "21:00",
    local: "Rua Princesa Isabel",
    descricao: "",
  },
  {
    id: 23,
    dia: "Sábado",
    data: "14/02",
    nome: "Bloco Eu Sozinho",
    horario: "22:00",
    local: "São Sebastião",
    descricao: "",
  },
  {
    id: 24,
    dia: "Sábado",
    data: "14/02",
    nome: "Bloco do Zé Pereira",
    horario: "19:30",
    local: "São Sebastião",
    descricao: "",
  },
  {
    id: 25,
    dia: "Domingo",
    data: "15/02",
    nome: "Boi Chorão",
    horario: "09:00",
    local: "Rua Siqueira Franca",
    descricao: "",
  },
  {
    id: 26,
    dia: "Domingo",
    data: "15/02",
    nome: "Ressuscita Facilita",
    horario: "15:00",
    local: "Boas Novas",
    descricao: "",
  },
  {
    id: 27,
    dia: "Domingo",
    data: "15/02",
    nome: "Bloco do Papangu",
    horario: "10:00",
    local: "São Sebastião",
    descricao: "",
  },
  {
    id: 28,
    dia: "Segunda",
    data: "16/02",
    nome: "Bloco das Catraias",
    horario: "09:00",
    local: "Encruzilhada - Campo de Futebol",
    descricao: "",
  },
  {
    id: 29,
    dia: "Segunda",
    data: "16/02",
    nome: "O Urso de vocês",
    horario: "10:00",
    local: "Bairro São Pedro",
    descricao: "",
  },
  {
    id: 30,
    dia: "Segunda",
    data: "16/02",
    nome: "Segura o Ovo",
    horario: "10:00",
    local: "Amarilis recepções e eventos",
    descricao: "",
  },
  {
    id: 31,
    dia: "Segunda",
    data: "16/02",
    nome: "As brilhosas",
    horario: "16:00",
    local: "São sebastião",
    descricao: "",
  },
  {
    id: 32,
    dia: "Segunda",
    data: "16/02",
    nome: "Bloco do Guarani",
    horario: "18:30",
    local: "Rua Antônio Bezerra",
    descricao: "",
  },
  {
    id: 33,
    dia: "Terça",
    data: "17/02",
    nome: "Boca de Álcool Folia",
    horario: "09:30",
    local: "Sítio Cajazeiras",
    descricao: "",
  },
  {
    id: 34,
    dia: "Terça",
    data: "17/02",
    nome: "Bloco Beijo",
    horario: "10:00",
    local: "Av. Francisca Lemos, S. Sebastião",
    descricao: "",
  },
  {
    id: 35,
    dia: "Terça",
    data: "17/02",
    nome: "Caiana Tropicana",
    horario: "10:00",
    local: "Av. Professor Amaral",
    descricao: "",
  },
  {
    id: 36,
    dia: "Terça",
    data: "17/02",
    nome: "Balança o Saco",
    horario: "10:00",
    local: "Quadra do Radar",
    descricao: "",
  },
  {
    id: 37,
    dia: "Terça",
    data: "17/02",
    nome: "Os 100 futuro",
    horario: "10:00",
    local: "Rua Sigismundo Gonçalves",
    descricao: "",
  },
  {
    id: 38,
    dia: "Terça",
    data: "17/02",
    nome: "Concentra mas não sai",
    horario: "11:00",
    local: "Av. Professor Amaral",
    descricao: "",
  },
  {
    id: 39,
    dia: "Terça",
    data: "17/02",
    nome: "As kengas da Cohab",
    horario: "17:00",
    local: "Cohab",
    descricao: "",
  },
  {
    id: 40,
    dia: "Terça",
    data: "17/02",
    nome: "As Melindrosas",
    horario: "20:00",
    local: "Rua 9 de Janeiro",
    descricao: "",
  },
  {
    id: 41,
    dia: "Quarta",
    data: "18/02",
    nome: "Peixada da confra",
    horario: "16:10",
    local: "Em frente a confraria",
    descricao: "",
  },
  {
    id: 42,
    dia: "Quarta",
    data: "18/02",
    nome: "Bacalhau do Lula Vassoureiro",
    horario: "20:30",
    local: "São Sebastião",
    descricao: "",
  },
  {
    id: 43,
    dia: "Domingo",
    data: "22/02",
    nome: "Carnaval do Santo Amaro 2",
    horario: "13:00",
    local: "Santo Amaro 2",
    descricao: "",
  },
  {
    id: 44,
    dia: "Domingo",
    data: "22/02",
    nome: "Só as cinzas",
    horario: "15:00",
    local: "Praça Centenária",
    descricao: "",
  },
  {
    id: 45,
    dia: "Domingo",
    data: "01/03",
    nome: "Bloco Infantil - Brincando de ser criança",
    horario: "15:00",
    local: "São Sebastião",
    descricao: "",
  },
];
