export const programacaoGeral = [
  // --- DIA 13/06 - SÁBADO ---
  {
    id: 1,
    dia: "Sábado",
    data: "13/06",
    palco: "Palco Principal",
    artista: "Ed Carlos",
    horario: "A definir",
  },
  {
    id: 2,
    dia: "Sábado",
    data: "13/06",
    palco: "Palco Principal",
    artista: "Marcão Noventta",
    horario: "A definir",
  },
  {
    id: 3,
    dia: "Sábado",
    data: "13/06",
    palco: "Palco Principal",
    artista: "Petrúcio Amorim",
    horario: "A definir",
  },
  {
    id: 4,
    dia: "Sábado",
    data: "13/06",
    palco: "Palco Principal",
    artista: "Waldonys",
    horario: "A definir",
  },
  {
    id: 5,
    dia: "Sábado",
    data: "13/06",
    palco: "Palco Principal",
    artista: "Transmissão - Jogo do Brasil",
    horario: "A definir",
  },

  // --- DIA 14/06 - DOMINGO ---
  {
    id: 6,
    dia: "Domingo",
    data: "14/06",
    palco: "Palco Principal",
    artista: "Luizinho Moreno",
    horario: "A definir",
  },
  {
    id: 7,
    dia: "Domingo",
    data: "14/06",
    palco: "Palco Principal",
    artista: "Daniel Gouveia",
    horario: "A definir",
  },
  {
    id: 8,
    dia: "Domingo",
    data: "14/06",
    palco: "Palco Principal",
    artista: "Victor Ferrari",
    horario: "A definir",
  },
  {
    id: 9,
    dia: "Domingo",
    data: "14/06",
    palco: "Palco Principal",
    artista: "Santanna - O Cantador",
    horario: "A definir",
  },
  {
    id: 10,
    dia: "Domingo",
    data: "14/06",
    palco: "Palco Principal",
    artista: "Anderson Alves",
    horario: "A definir",
  },

  // --- DIA 20/06 - SÁBADO ---
  {
    id: 11,
    dia: "Sábado",
    data: "20/06",
    palco: "Palco Principal",
    artista: "Ciel Santos",
    horario: "A definir",
  },
  {
    id: 12,
    dia: "Sábado",
    data: "20/06",
    palco: "Palco Principal",
    artista: "Josildo Sá",
    horario: "A definir",
  },
  {
    id: 13,
    dia: "Sábado",
    data: "20/06",
    palco: "Palco Principal",
    artista: "Assisão",
    horario: "A definir",
  },
  {
    id: 14,
    dia: "Sábado",
    data: "20/06",
    palco: "Palco Principal",
    artista: "Emerson Cavalcante",
    horario: "A definir",
  },

  // --- DIA 21/06 - DOMINGO ---
  {
    id: 15,
    dia: "Domingo",
    data: "21/06",
    palco: "Palco Principal",
    artista: "Fabiana Pimentinha",
    horario: "A definir",
  },
  {
    id: 16,
    dia: "Domingo",
    data: "21/06",
    palco: "Palco Principal",
    artista: "Henrique Barbosa",
    horario: "A definir",
  },
  {
    id: 17,
    dia: "Domingo",
    data: "21/06",
    palco: "Palco Principal",
    artista: "Almir Rouche",
    horario: "A definir",
  },
  {
    id: 18,
    dia: "Domingo",
    data: "21/06",
    palco: "Palco Principal",
    artista: "Assum Preto",
    horario: "A definir",
  },
  {
    id: 19,
    dia: "Domingo",
    data: "21/06",
    palco: "Palco Principal",
    artista: "Higor Henrique",
    horario: "A definir",
  },

  // --- DIA 23/06 - TERÇA ---
  {
    id: 20,
    dia: "Terça",
    data: "23/06",
    palco: "Palco Principal",
    artista: "Samara Costa",
    horario: "A definir",
  },
  {
    id: 21,
    dia: "Terça",
    data: "23/06",
    palco: "Palco Principal",
    artista: "Dudu do Acordeon (part.)",
    horario: "A definir",
  },
  {
    id: 22,
    dia: "Terça",
    data: "23/06",
    palco: "Palco Principal",
    artista: "Jorge de Altinho",
    horario: "A definir",
  },
  {
    id: 23,
    dia: "Terça",
    data: "23/06",
    palco: "Palco Principal",
    artista: "Geraldinho Lins",
    horario: "A definir",
  },
  {
    id: 24,
    dia: "Terça",
    data: "23/06",
    palco: "Palco Principal",
    artista: "Bruninho Lima (part.)",
    horario: "A definir",
  },

  // --- DIA 24/06 - QUARTA ---
  {
    id: 25,
    dia: "Quarta",
    data: "24/06",
    palco: "Palco Principal",
    artista: "Silvério Pessoa",
    horario: "A definir",
  },
  {
    id: 26,
    dia: "Quarta",
    data: "24/06",
    palco: "Palco Principal",
    artista: "Joyce Alane",
    horario: "A definir",
  },
  {
    id: 27,
    dia: "Quarta",
    data: "24/06",
    palco: "Palco Principal",
    artista: "Juarez",
    horario: "A definir",
  },
  {
    id: 28,
    dia: "Quarta",
    data: "24/06",
    palco: "Palco Principal",
    artista: "Lady Falcão",
    horario: "A definir",
  },
  {
    id: 29,
    dia: "Quarta",
    data: "24/06",
    palco: "Palco Principal",
    artista: "Transmissão - Jogo do Brasil",
    horario: "A definir",
  },

  // --- DIA 27/06 - SÁBADO ---
  {
    id: 30,
    dia: "Sábado",
    data: "27/06",
    palco: "Palco Principal",
    artista: "Rei do Cangaço",
    horario: "A definir",
  },
  {
    id: 31,
    dia: "Sábado",
    data: "27/06",
    palco: "Palco Principal",
    artista: "Irah Caldeira",
    horario: "A definir",
  },
  {
    id: 32,
    dia: "Sábado",
    data: "27/06",
    palco: "Palco Principal",
    artista: "Amazan",
    horario: "A definir",
  },
  {
    id: 33,
    dia: "Sábado",
    data: "27/06",
    palco: "Palco Principal",
    artista: "Cristina Amaral",
    horario: "A definir",
  },
  {
    id: 34,
    dia: "Sábado",
    data: "27/06",
    palco: "Palco Principal",
    artista: "Walter Lins",
    horario: "A definir",
  },

  // --- DIA 28/06 - DOMINGO ---
  {
    id: 35,
    dia: "Domingo",
    data: "28/06",
    palco: "Palco Principal",
    artista: "Morganna Bernardo",
    horario: "A definir",
  },
  {
    id: 36,
    dia: "Domingo",
    data: "28/06",
    palco: "Palco Principal",
    artista: "Flávio Leandro",
    horario: "A definir",
  },
  {
    id: 37,
    dia: "Domingo",
    data: "28/06",
    palco: "Palco Principal",
    artista: "Pau no Xote",
    horario: "A definir",
  },
  {
    id: 38,
    dia: "Domingo",
    data: "28/06",
    palco: "Palco Principal",
    artista: "Cezzinha",
    horario: "A definir",
  },
  {
    id: 39,
    dia: "Domingo",
    data: "28/06",
    palco: "Palco Principal",
    artista: "Amannda Leão",
    horario: "A definir",
  },
];
