export const programacaoGeral = [
  // ==========================================
  //            PALCO PRINCIPAL
  // ==========================================

  // --- DIA 13/06 - SÁBADO ---
  {
    id: 1,
    dia: "Sábado",
    data: "13/06",
    palco: "Palco Principal",
    artista: "Ed Carlos",
    horario: "12:00",
  },
  {
    id: 2,
    dia: "Sábado",
    data: "13/06",
    palco: "Palco Principal",
    artista: "Marcão Noventta",
    horario: "14:00",
  },
  {
    id: 3,
    dia: "Sábado",
    data: "13/06",
    palco: "Palco Principal",
    artista: "Petrúcio Amorim",
    horario: "16:00",
  },
  {
    id: 4,
    dia: "Sábado",
    data: "13/06",
    palco: "Palco Principal",
    artista: "Waldonys",
    horario: "18:00",
  },
  {
    id: 5,
    dia: "Sábado",
    data: "13/06",
    palco: "Palco Principal",
    artista: "Transmissão - Jogo do Brasil",
    horario: "20:00",
  },

  // --- DIA 14/06 - DOMINGO ---
  {
    id: 6,
    dia: "Domingo",
    data: "14/06",
    palco: "Palco Principal",
    artista: "Luizinho Moreno",
    horario: "12:00",
  },
  {
    id: 7,
    dia: "Domingo",
    data: "14/06",
    palco: "Palco Principal",
    artista: "Daniel Gouveia",
    horario: "14:00",
  },
  {
    id: 8,
    dia: "Domingo",
    data: "14/06",
    palco: "Palco Principal",
    artista: "Victor Ferrari",
    horario: "16:00",
  },
  {
    id: 9,
    dia: "Domingo",
    data: "14/06",
    palco: "Palco Principal",
    artista: "Santanna - O Cantador",
    horario: "18:00",
  },
  {
    id: 10,
    dia: "Domingo",
    data: "14/06",
    palco: "Palco Principal",
    artista: "Anderson Alves",
    horario: "20:00",
  },

  // --- DIA 20/06 - SÁBADO ---
  {
    id: 11,
    dia: "Sábado",
    data: "20/06",
    palco: "Palco Principal",
    artista: "Ciel Santos",
    horario: "12:00",
  },
  {
    id: 12,
    dia: "Sábado",
    data: "20/06",
    palco: "Palco Principal",
    artista: "Assisão",
    horario: "14:00",
  },
  {
    id: 13,
    dia: "Sábado",
    data: "20/06",
    palco: "Palco Principal",
    artista: "Benil",
    horario: "16:00",
  },
  {
    id: 14,
    dia: "Sábado",
    data: "20/06",
    palco: "Palco Principal",
    artista: "Josildo Sá",
    horario: "18:00",
  },
  {
    id: 15,
    dia: "Sábado",
    data: "20/06",
    palco: "Palco Principal",
    artista: "Emerson Cavalcante",
    horario: "20:00",
  },

  // --- DIA 21/06 - DOMINGO ---
  {
    id: 16,
    dia: "Domingo",
    data: "21/06",
    palco: "Palco Principal",
    artista: "Fabiana Pimentinha",
    horario: "12:00",
  },
  {
    id: 17,
    dia: "Domingo",
    data: "21/06",
    palco: "Palco Principal",
    artista: "Henrique Barbosa",
    horario: "14:00",
  },
  {
    id: 18,
    dia: "Domingo",
    data: "21/06",
    palco: "Palco Principal",
    artista: "Almir Rouche",
    horario: "16:00",
  },
  {
    id: 19,
    dia: "Domingo",
    data: "21/06",
    palco: "Palco Principal",
    artista: "Assum Preto",
    horario: "18:00",
  },
  {
    id: 20,
    dia: "Domingo",
    data: "21/06",
    palco: "Palco Principal",
    artista: "Higor Henrique",
    horario: "20:00",
  },

  // --- DIA 23/06 - TERÇA ---
  {
    id: 21,
    dia: "Terça",
    data: "23/06",
    palco: "Palco Principal",
    artista: "Samara Costa",
    horario: "12:00",
  },
  {
    id: 22,
    dia: "Terça",
    data: "23/06",
    palco: "Palco Principal",
    artista: "Dudu do Acordeon (part.)",
    horario: "14:00",
  },
  {
    id: 23,
    dia: "Terça",
    data: "23/06",
    palco: "Palco Principal",
    artista: "Jorge de Altinho",
    horario: "16:00",
  },
  {
    id: 24,
    dia: "Terça",
    data: "23/06",
    palco: "Palco Principal",
    artista: "Geraldinho Lins",
    horario: "18:00",
  },
  {
    id: 25,
    dia: "Terça",
    data: "23/06",
    palco: "Palco Principal",
    artista: "Bruninho Lima (part.)",
    horario: "20:00",
  },

  // --- DIA 24/06 - QUARTA ---
  {
    id: 26,
    dia: "Quarta",
    data: "24/06",
    palco: "Palco Principal",
    artista: "Silvério Pessoa",
    horario: "12:00",
  },
  {
    id: 27,
    dia: "Quarta",
    data: "24/06",
    palco: "Palco Principal",
    artista: "Joyce Alane",
    horario: "14:00",
  },
  {
    id: 28,
    dia: "Quarta",
    data: "24/06",
    palco: "Palco Principal",
    artista: "Juarez",
    horario: "16:00",
  },
  {
    id: 29,
    dia: "Quarta",
    data: "24/06",
    palco: "Palco Principal",
    artista: "Lady Falcão",
    horario: "18:00",
  },
  {
    id: 30,
    dia: "Quarta",
    data: "24/06",
    palco: "Palco Principal",
    artista: "Transmissão - Jogo do Brasil",
    horario: "20:00",
  },

  // --- DIA 27/06 - SÁBADO ---
  {
    id: 31,
    dia: "Sábado",
    data: "27/06",
    palco: "Palco Principal",
    artista: "Rei do Cangaço",
    horario: "12:00",
  },
  {
    id: 32,
    dia: "Sábado",
    data: "27/06",
    palco: "Palco Principal",
    artista: "Irah Caldeira",
    horario: "14:00",
  },
  {
    id: 33,
    dia: "Sábado",
    data: "27/06",
    palco: "Palco Principal",
    artista: "Amazan",
    horario: "16:00",
  },
  {
    id: 34,
    dia: "Sábado",
    data: "27/06",
    palco: "Palco Principal",
    artista: "Cristina Amaral",
    horario: "18:00",
  },
  {
    id: 35,
    dia: "Sábado",
    data: "27/06",
    palco: "Palco Principal",
    artista: "Walter Lins",
    horario: "20:00",
  },

  // --- DIA 28/06 - DOMINGO ---
  {
    id: 36,
    dia: "Domingo",
    data: "28/06",
    palco: "Palco Principal",
    artista: "Morganna Bernardo",
    horario: "12:00",
  },
  {
    id: 37,
    dia: "Domingo",
    data: "28/06",
    palco: "Palco Principal",
    artista: "Flávio Leandro",
    horario: "14:00",
  },
  {
    id: 38,
    dia: "Domingo",
    data: "28/06",
    palco: "Palco Principal",
    artista: "Pau no Xote",
    horario: "16:00",
  },
  {
    id: 39,
    dia: "Domingo",
    data: "28/06",
    palco: "Palco Principal",
    artista: "Cezzinha",
    horario: "18:00",
  },
  {
    id: 40,
    dia: "Domingo",
    data: "28/06",
    palco: "Palco Principal",
    artista: "Amannda Leão",
    horario: "20:00",
  },

  // ==========================================
  //             PALCO CULTURAL
  // ==========================================

  // --- DIA 13/06 - SÁBADO ---
  {
    id: 41,
    dia: "Sábado",
    data: "13/06",
    palco: "Palco Cultural",
    artista: "Quadrilha Folclopopular",
    horario: "13:00",
  },
  {
    id: 42,
    dia: "Sábado",
    data: "13/06",
    palco: "Palco Cultural",
    artista: "Clara Ellys",
    horario: "14:00",
  },
  {
    id: 43,
    dia: "Sábado",
    data: "13/06",
    palco: "Palco Cultural",
    artista: "Batalhão 44",
    horario: "15:30",
  },
  {
    id: 44,
    dia: "Sábado",
    data: "13/06",
    palco: "Palco Cultural",
    artista: "Wanessa Roger",
    horario: "16:30",
  },
  {
    id: 45,
    dia: "Sábado",
    data: "13/06",
    palco: "Palco Cultural",
    artista: "Junina Bacelar Riacho",
    horario: "18:00",
  },

  // --- DIA 14/06 - DOMINGO ---
  {
    id: 46,
    dia: "Domingo",
    data: "14/06",
    palco: "Palco Cultural",
    artista: "Quadrilha Paranguarte",
    horario: "13:00",
  },
  {
    id: 47,
    dia: "Domingo",
    data: "14/06",
    palco: "Palco Cultural",
    artista: "Zé Barreto",
    horario: "14:00",
  },
  {
    id: 48,
    dia: "Domingo",
    data: "14/06",
    palco: "Palco Cultural",
    artista: "Junina Asa Branca (Ameixas)",
    horario: "15:30",
  },
  {
    id: 49,
    dia: "Domingo",
    data: "14/06",
    palco: "Palco Cultural",
    artista: "Marcos Montez",
    horario: "16:30",
  },
  {
    id: 50,
    dia: "Domingo",
    data: "14/06",
    palco: "Palco Cultural",
    artista: "Jamile Oliveira",
    horario: "18:00",
  },

  // --- DIA 20/06 - SÁBADO ---
  {
    id: 51,
    dia: "Sábado",
    data: "20/06",
    palco: "Palco Cultural",
    artista: "Junina Luar Serra Negra",
    horario: "13:00",
  },
  {
    id: 52,
    dia: "Sábado",
    data: "20/06",
    palco: "Palco Cultural",
    artista: "Eu, Tu e Elas",
    horario: "14:00",
  },
  {
    id: 53,
    dia: "Sábado",
    data: "20/06",
    palco: "Palco Cultural",
    artista: "Batalhão 44",
    horario: "16:30",
  } /* PDF original marcava 16:30 para este */,
  {
    id: 54,
    dia: "Sábado",
    data: "20/06",
    palco: "Palco Cultural",
    artista: "Michel Deniz",
    horario: "18:00",
  },

  // --- DIA 21/06 - DOMINGO ---
  {
    id: 55,
    dia: "Domingo",
    data: "21/06",
    palco: "Palco Cultural",
    artista: "Quadrilha Folclopopular",
    horario: "13:00",
  },
  {
    id: 56,
    dia: "Domingo",
    data: "21/06",
    palco: "Palco Cultural",
    artista: "Vitória do Pife",
    horario: "14:00",
  },
  {
    id: 57,
    dia: "Domingo",
    data: "21/06",
    palco: "Palco Cultural",
    artista: "Junina Luar da Serra Negra",
    horario: "15:30",
  },
  {
    id: 58,
    dia: "Domingo",
    data: "21/06",
    palco: "Palco Cultural",
    artista: "Elian do Acordeon",
    horario: "16:30",
  },
  {
    id: 59,
    dia: "Domingo",
    data: "21/06",
    palco: "Palco Cultural",
    artista: "Marcelo Thalentos",
    horario: "18:00",
  },

  // --- DIA 23/06 - TERÇA ---
  {
    id: 60,
    dia: "Terça",
    data: "23/06",
    palco: "Palco Cultural",
    artista: "Quadrilha Paranguarte",
    horario: "13:00",
  },
  {
    id: 61,
    dia: "Terça",
    data: "23/06",
    palco: "Palco Cultural",
    artista: "Douglas Leon",
    horario: "14:00",
  },
  {
    id: 62,
    dia: "Terça",
    data: "23/06",
    palco: "Palco Cultural",
    artista: "Batalhão 44",
    horario: "15:30",
  },
  {
    id: 63,
    dia: "Terça",
    data: "23/06",
    palco: "Palco Cultural",
    artista: "Junina Bacelar Riacho",
    horario: "16:30",
  },
  {
    id: 64,
    dia: "Terça",
    data: "23/06",
    palco: "Palco Cultural",
    artista: "Elys Viana",
    horario: "18:00",
  },

  // --- DIA 24/06 - QUARTA ---
  {
    id: 65,
    dia: "Quarta",
    data: "24/06",
    palco: "Palco Cultural",
    artista: "Quadrilha Folclopopular",
    horario: "13:00",
  },
  {
    id: 66,
    dia: "Quarta",
    data: "24/06",
    palco: "Palco Cultural",
    artista: "Renilda Cardoso",
    horario: "14:00",
  },
  {
    id: 67,
    dia: "Quarta",
    data: "24/06",
    palco: "Palco Cultural",
    artista: "Junina Luar Serra Negra",
    horario: "15:30",
  },
  {
    id: 68,
    dia: "Quarta",
    data: "24/06",
    palco: "Palco Cultural",
    artista: "Forró Candeeiro Encantado",
    horario: "16:30",
  },
  {
    id: 69,
    dia: "Quarta",
    data: "24/06",
    palco: "Palco Cultural",
    artista: "Anny Sales",
    horario: "18:00",
  },

  // --- DIA 27/06 - SÁBADO ---
  {
    id: 70,
    dia: "Sábado",
    data: "27/06",
    palco: "Palco Cultural",
    artista: "Quadrilha Paranguarte",
    horario: "13:00",
  },
  {
    id: 71,
    dia: "Sábado",
    data: "27/06",
    palco: "Palco Cultural",
    artista: "Patrícia Alves",
    horario: "14:00",
  },
  {
    id: 72,
    dia: "Sábado",
    data: "27/06",
    palco: "Palco Cultural",
    artista: "Batalhão 44",
    horario: "15:30",
  },
  {
    id: 73,
    dia: "Sábado",
    data: "27/06",
    palco: "Palco Cultural",
    artista: "Patrícia Vasconcelos",
    horario: "16:30",
  },
  {
    id: 74,
    dia: "Sábado",
    data: "27/06",
    palco: "Palco Cultural",
    artista: "Carlinhos Melo",
    horario: "18:00",
  },

  // --- DIA 28/06 - DOMINGO ---
  {
    id: 75,
    dia: "Domingo",
    data: "28/06",
    palco: "Palco Cultural",
    artista: "Quadrilha Folclopopular",
    horario: "13:00",
  },
  {
    id: 76,
    dia: "Domingo",
    data: "28/06",
    palco: "Palco Cultural",
    artista: "Elas Cantam Gonzaga",
    horario: "14:00",
  },
  {
    id: 77,
    dia: "Domingo",
    data: "28/06",
    palco: "Palco Cultural",
    artista: "Batalhão 44",
    horario: "15:30",
  },
  {
    id: 78,
    dia: "Domingo",
    data: "28/06",
    palco: "Palco Cultural",
    artista: "Leninho Filho",
    horario: "16:30",
  },
];
